# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/georgegunther/Desktop/n22/n22.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 310)
        MainWindow.setMinimumSize(QtCore.QSize(480, 300))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 350))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 30, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 150, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 180, 161, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 210, 181, 16))
        self.label_8.setObjectName("label_8")
        self.buttonotvet = QtWidgets.QPushButton(self.centralwidget)
        self.buttonotvet.setGeometry(QtCore.QRect(120, 240, 231, 41))
        self.buttonotvet.setObjectName("buttonotvet")
        self.otvet = QtWidgets.QTextEdit(self.centralwidget)
        self.otvet.setGeometry(QtCore.QRect(360, 240, 101, 31))
        self.otvet.setMaximumSize(QtCore.QSize(10000000, 10000000))
        self.otvet.setObjectName("otvet")
        self.spinchislo1 = QtWidgets.QComboBox(self.centralwidget)
        self.spinchislo1.setGeometry(QtCore.QRect(150, 60, 241, 26))
        self.spinchislo1.setObjectName("spinchislo1")
        self.spinchislo1.addItem("")
        self.spinchislo1.addItem("")
        self.spinchislo1.addItem("")
        self.spinchislo1.addItem("")
        self.spinchislo1.addItem("")
        self.spinchislo1.addItem("")
        self.spinchislo1.addItem("")
        self.spinchislo1.addItem("")
        self.spinchislo1.addItem("")
        self.spinchislo2 = QtWidgets.QComboBox(self.centralwidget)
        self.spinchislo2.setGeometry(QtCore.QRect(150, 90, 241, 26))
        self.spinchislo2.setObjectName("spinchislo2")
        self.spinchislo2.addItem("")
        self.spinchislo2.addItem("")
        self.spinchislo2.addItem("")
        self.spinchislo2.addItem("")
        self.spinchislo2.addItem("")
        self.spinchislo2.addItem("")
        self.spinchislo2.addItem("")
        self.spinchislo2.addItem("")
        self.spinchislo2.addItem("")
        self.spinchislo3 = QtWidgets.QComboBox(self.centralwidget)
        self.spinchislo3.setGeometry(QtCore.QRect(150, 120, 241, 26))
        self.spinchislo3.setObjectName("spinchislo3")
        self.spinchislo3.addItem("")
        self.spinchislo3.addItem("")
        self.spinchislo3.addItem("")
        self.spinchislo3.addItem("")
        self.spinchislo3.addItem("")
        self.spinchislo3.addItem("")
        self.spinchislo3.addItem("")
        self.spinchislo3.addItem("")
        self.spinchislo3.addItem("")
        self.spinchislo4 = QtWidgets.QComboBox(self.centralwidget)
        self.spinchislo4.setGeometry(QtCore.QRect(150, 150, 241, 26))
        self.spinchislo4.setObjectName("spinchislo4")
        self.spinchislo4.addItem("")
        self.spinchislo4.addItem("")
        self.spinchislo4.addItem("")
        self.spinchislo4.addItem("")
        self.spinchislo4.addItem("")
        self.spinchislo4.addItem("")
        self.spinchislo4.addItem("")
        self.spinchislo4.addItem("")
        self.spinchislo4.addItem("")
        self.a = QtWidgets.QLineEdit(self.centralwidget)
        self.a.setGeometry(QtCore.QRect(140, 30, 61, 21))
        self.a.setStatusTip("")
        self.a.setObjectName("a")
        self.b = QtWidgets.QLineEdit(self.centralwidget)
        self.b.setGeometry(QtCore.QRect(340, 30, 61, 21))
        self.b.setObjectName("b")
        self.chislo2 = QtWidgets.QLineEdit(self.centralwidget)
        self.chislo2.setGeometry(QtCore.QRect(400, 90, 61, 21))
        self.chislo2.setObjectName("chislo2")
        self.chislo3 = QtWidgets.QLineEdit(self.centralwidget)
        self.chislo3.setGeometry(QtCore.QRect(400, 120, 61, 21))
        self.chislo3.setObjectName("chislo3")
        self.chislo4 = QtWidgets.QLineEdit(self.centralwidget)
        self.chislo4.setGeometry(QtCore.QRect(400, 150, 61, 21))
        self.chislo4.setObjectName("chislo4")
        self.sod = QtWidgets.QLineEdit(self.centralwidget)
        self.sod.setGeometry(QtCore.QRect(210, 180, 61, 21))
        self.sod.setObjectName("sod")
        self.nesod = QtWidgets.QLineEdit(self.centralwidget)
        self.nesod.setGeometry(QtCore.QRect(210, 210, 61, 21))
        self.nesod.setObjectName("nesod")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(360, 170, 71, 81))
        self.label_9.setObjectName("label_9")
        self.chislo1 = QtWidgets.QLineEdit(self.centralwidget)
        self.chislo1.setGeometry(QtCore.QRect(400, 60, 59, 21))
        self.chislo1.setObjectName("chislo1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.spinchislo1.currentIndexChanged['int'].connect(self.chislo1.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вычисление траекторий"))
        self.label.setText(_translate("MainWindow", "Исходное число"))
        self.label_2.setText(_translate("MainWindow", "Конечное число"))
        self.label_3.setText(_translate("MainWindow", "Первая опция"))
        self.label_4.setText(_translate("MainWindow", "Вторая опция"))
        self.label_5.setText(_translate("MainWindow", "Третья опция"))
        self.label_6.setText(_translate("MainWindow", "Четвертая опция"))
        self.label_7.setText(_translate("MainWindow", "Траектория СОДЕРЖИТ"))
        self.label_8.setText(_translate("MainWindow", "Траектория НЕ СОДЕРЖИТ"))
        self.buttonotvet.setText(_translate("MainWindow", "Вычислить"))
        self.otvet.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#6b6b6b;\">Ответ: 55</span></p></body></html>"))
        self.spinchislo1.setItemText(0, _translate("MainWindow", "прибавь"))
        self.spinchislo1.setItemText(1, _translate("MainWindow", "вычти"))
        self.spinchislo1.setItemText(2, _translate("MainWindow", "умножь"))
        self.spinchislo1.setItemText(3, _translate("MainWindow", "возведи в квадрат"))
        self.spinchislo1.setItemText(4, _translate("MainWindow", "увеличь старшую цифру числа на 1"))
        self.spinchislo1.setItemText(5, _translate("MainWindow", "сделай четное"))
        self.spinchislo1.setItemText(6, _translate("MainWindow", "сделай нечетное"))
        self.spinchislo1.setItemText(7, _translate("MainWindow", "прибавь предыдущее"))
        self.spinchislo1.setItemText(8, _translate("MainWindow", "прибавь следующее"))
        self.spinchislo2.setItemText(0, _translate("MainWindow", "прибавь"))
        self.spinchislo2.setItemText(1, _translate("MainWindow", "вычти"))
        self.spinchislo2.setItemText(2, _translate("MainWindow", "умножь"))
        self.spinchislo2.setItemText(3, _translate("MainWindow", "возведи в квадрат"))
        self.spinchislo2.setItemText(4, _translate("MainWindow", "увеличь старшую цифру числа на 1"))
        self.spinchislo2.setItemText(5, _translate("MainWindow", "сделай четное"))
        self.spinchislo2.setItemText(6, _translate("MainWindow", "сделай нечетное"))
        self.spinchislo2.setItemText(7, _translate("MainWindow", "прибавь предыдущее"))
        self.spinchislo2.setItemText(8, _translate("MainWindow", "прибавь следующее"))
        self.spinchislo3.setItemText(0, _translate("MainWindow", "прибавь"))
        self.spinchislo3.setItemText(1, _translate("MainWindow", "вычти"))
        self.spinchislo3.setItemText(2, _translate("MainWindow", "умножь"))
        self.spinchislo3.setItemText(3, _translate("MainWindow", "возведи в квадрат"))
        self.spinchislo3.setItemText(4, _translate("MainWindow", "увеличь старшую цифру числа на 1"))
        self.spinchislo3.setItemText(5, _translate("MainWindow", "сделай четное"))
        self.spinchislo3.setItemText(6, _translate("MainWindow", "сделай нечетное"))
        self.spinchislo3.setItemText(7, _translate("MainWindow", "прибавь предыдущее"))
        self.spinchislo3.setItemText(8, _translate("MainWindow", "прибавь следующее"))
        self.spinchislo4.setItemText(0, _translate("MainWindow", "прибавь"))
        self.spinchislo4.setItemText(1, _translate("MainWindow", "вычти"))
        self.spinchislo4.setItemText(2, _translate("MainWindow", "умножь"))
        self.spinchislo4.setItemText(3, _translate("MainWindow", "возведи в квадрат"))
        self.spinchislo4.setItemText(4, _translate("MainWindow", "увеличь старшую цифру числа на 1"))
        self.spinchislo4.setItemText(5, _translate("MainWindow", "сделай четное"))
        self.spinchislo4.setItemText(6, _translate("MainWindow", "сделай нечетное"))
        self.spinchislo4.setItemText(7, _translate("MainWindow", "прибавь предыдущее"))
        self.spinchislo4.setItemText(8, _translate("MainWindow", "прибавь следующее"))
        self.a.setText(_translate("MainWindow", "1"))
        self.b.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#6a6a6a;\">10</span></p></body></html>"))
        self.b.setText(_translate("MainWindow", "10"))
        self.chislo2.setText(_translate("MainWindow", "2"))
        self.chislo3.setText(_translate("MainWindow", "0"))
        self.chislo4.setText(_translate("MainWindow", "0"))
        self.sod.setText(_translate("MainWindow", "0"))
        self.nesod.setText(_translate("MainWindow", "0"))
        self.label_9.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/kitty/IMG_0910.JPG\"/></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/kitty/kisspng-persian-cat-maine-coon-birman-kitten-pet-persian-5abfd68016c311.8809861615225217280932 copy.png\"/></p></body></html>"))
        self.chislo1.setText(_translate("MainWindow", "1"))

import image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

